# Generated by Django 2.2.1 on 2019-05-13 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trigram', '0003_auto_20190513_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modela',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='modelb',
            name='first_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='modelb',
            name='last_name',
            field=models.CharField(max_length=255),
        ),
    ]
